<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-12-26 13:50
=======
# Generated by Django 5.0.14 on 2025-12-26 06:49
>>>>>>> origin/NhatNguyen

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Mã định danh vị trí, ví dụ: homepage_top, sidebar_right', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_banners', models.PositiveIntegerField(default=1)),
                ('width_hint', models.IntegerField(default=0, help_text='Chiều rộng gợi ý (px)')),
                ('height_hint', models.IntegerField(default=0, help_text='Chiều cao gợi ý (px)')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/')),
                ('click_url', models.URLField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-start_at'],
            },
        ),
    ]
