# Generated by Django 5.0.14 on 2025-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='height_hint',
            field=models.IntegerField(default=0, help_text='Chiều cao gợi ý (px)'),
        ),
        migrations.AddField(
            model_name='adslot',
            name='width_hint',
            field=models.IntegerField(default=0, help_text='Chiều rộng gợi ý (px)'),
        ),
    ]
