# Generated by Django 5.0.14 on 2025-11-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Mã định danh vị trí, ví dụ: homepage_top, sidebar_right', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_banners', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='target_category',
        ),
        migrations.AddField(
            model_name='banner',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='marketing.adslot'),
            preserve_default=False,
        ),
    ]
