# Generated by Django 5.0.14 on 2025-12-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adslot',
            name='height_hint',
        ),
        migrations.RemoveField(
            model_name='adslot',
            name='width_hint',
        ),
    ]
