# Generated by Django 5.0.14 on 2025-12-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_adslot_remove_banner_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='code',
            field=models.SlugField(choices=[('homepage_top', 'Đầu trang chủ (Homepage Top)'), ('sidebar_right', 'Thanh bên phải (Sidebar Right)'), ('footer', 'Chân trang (Footer)'), ('in_article', 'Trong bài viết (In Article)')], default='homepage_top', help_text='Chọn mã định danh vị trí từ danh sách có sẵn', unique=True),
        ),
    ]
