# Generated by Django 5.0.14 on 2025-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_adslot_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='code',
            field=models.SlugField(help_text='Mã định danh vị trí, ví dụ: homepage_top, sidebar_right', unique=True),
        ),
    ]
