# Generated by Django 5.0.14 on 2025-12-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_created', 'Đơn hàng mới'), ('order_status_changed', 'Cập nhật đơn hàng'), ('chat', 'Tin nhắn'), ('system', 'Hệ thống'), ('promo', 'Khuyến mãi'), ('payment', 'Thanh toán')], default='system', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
