# Generated by Django 5.0.14 on 2025-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_created', 'Đơn hàng mới'), ('order_status_changed', 'Cập nhật đơn hàng'), ('chat', 'Tin nhắn'), ('system', 'Hệ thống'), ('promo', 'Khuyến mãi'), ('payment', 'Thanh toán')], default='system', max_length=50),
        ),
    ]
