<<<<<<< HEAD
=======
# Generated by Django 5.0.14 on 2025-12-25 04:23
>>>>>>> origin/ChiTham

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('payment_method', models.CharField(blank=True, default='Thanh toán khi nhận hàng (COD)', max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='unpaid', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Mã giao dịch từ VNPAY/Momo/Ngân hàng', max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Thời điểm thanh toán thành công', null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang vận chuyển'), ('delivered', 'Đã giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('returned', 'Trả hàng/Hoàn tiền')], default='pending', max_length=50)),
                ('is_disputed', models.BooleanField(default=False)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('sold_counted', models.BooleanField(default=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ghn_order_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.URLField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('NORMAL', 'Bình thường'), ('REFUND_REQUESTED', 'Yêu cầu hoàn tiền'), ('WAITING_RETURN', 'Chờ trả hàng'), ('RETURNING', 'Đang trả hàng về'), ('SELLER_REJECTED', 'Người bán từ chối'), ('DISPUTE_TO_ADMIN', 'Khiếu nại lên Sàn'), ('REFUND_APPROVED', 'Đồng ý hoàn tiền'), ('REFUND_REJECTED', 'Từ chối hoàn tiền')], default='NORMAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('preorder_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
