# Generated by Django 5.0.14 on 2025-12-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Bình thường'), ('REFUND_REQUESTED', 'Yêu cầu hoàn tiền'), ('WAITING_RETURN', 'Chờ trả hàng'), ('RETURNING', 'Đang trả hàng về'), ('SELLER_REJECTED', 'Người bán từ chối'), ('DISPUTE_TO_ADMIN', 'Khiếu nại lên Sàn'), ('REFUND_APPROVED', 'Đồng ý hoàn tiền'), ('REFUND_REJECTED', 'Từ chối hoàn tiền')], default='NORMAL', max_length=50),
        ),
    ]
