# Generated by Django 5.0.14 on 2025-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district_id',
            field=models.IntegerField(blank=True, help_text='GHN DistrictID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='province_id',
            field=models.IntegerField(blank=True, help_text='GHN ProvinceID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ward_code',
            field=models.CharField(blank=True, help_text='GHN WardCode', max_length=20, null=True),
        ),
    ]
