<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-09-11 08:38
=======

>>>>>>> b649ab7c6fdfd31ea20509cf3abff52781d5a333

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
<<<<<<< HEAD
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
=======
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('success', 'Success'),
                    ('cancelled', 'Cancelled')
                ],
                default='pending',
                max_length=20,
            ),
>>>>>>> b649ab7c6fdfd31ea20509cf3abff52781d5a333
        ),
    ]
