# Generated by Django 5.0.14 on 2025-11-01 00:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0010_alter_product_ordered_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preorder',
            unique_together={('user', 'product')},
        ),
    ]
