# Generated by Django 5.0.14 on 2025-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_preorder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold_counted',
            field=models.BooleanField(default=False),
        ),
    ]
