# Generated by Django 5.0.14 on 2025-09-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
