# Generated by Django 5.0.14 on 2025-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_stock_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('success', 'Success'), ('cancelled', 'Cancelled'), ('ready_to_pick', 'created'), ('picking', 'picking'), ('delivered', 'delivered'), ('delivering', 'out_for_delivery'), ('delevery_fail', 'delevery_failed'), ('lost', 'lost'), ('damage', 'damage'), ('return', 'return')], default='pending', max_length=20),
        ),
    ]
