# Generated by Django 5.0.14 on 2025-09-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ghn_order_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('success', 'Success'), ('cancelled', 'Cancelled'), ('ready_to_pick', 'created'), ('picking', 'picking'), ('delivered', 'delivered'), ('delivering', 'out_for_delivery'), ('delivery_fail', 'delevery_failed'), ('lost', 'lost'), ('damage', 'damage'), ('return', 'return')], default='pending', max_length=20),
        ),
    ]
