# Generated by Django 5.0.14 on 2025-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('delivery', 'Delivery pending'), ('success', 'Success'), ('cancelled', 'Cancelled'), ('ready_to_pick', 'Ready to pick'), ('picking', 'Picking'), ('delivered', 'Delivered'), ('out_for_delivery', 'Out for delivery'), ('delivery_failed', 'Delivery failed'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
