# Generated by Django 5.0.14 on 2025-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối'), ('lock', 'Bị khoá')], default='pending', max_length=20),
        ),
    ]
