# Generated by Django 5.0.14 on 2025-12-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='ward_code',
        ),
    ]
