# Generated by Django 5.0.14 on 2025-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='pending', max_length=20),
        ),
    ]
