# Generated by Django 5.0.14 on 2025-11-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_seller_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Đăng nhập'), ('add_product', 'Thêm sản phẩm'), ('update_product', 'Cập nhật sản phẩm'), ('delete_product', 'Xóa sản phẩm'), ('order_success', 'Hoàn tất đơn hàng'), ('account_locked', 'Tài khoản bị khóa'), ('account_unlocked', 'Tài khoản được mở'), ('profile_updated', 'Cập nhật hồ sơ'), ('other', 'Khác')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='sellers.seller')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
