# Generated by Django 5.0.14 on 2025-11-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_selleractivitylog_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('add_product', 'Thêm sản phẩm'), ('update_product', 'Cập nhật sản phẩm'), ('delete_product', 'Xóa sản phẩm'), ('order_success', 'Hoàn tất đơn hàng'), ('account_locked', 'Tài khoản bị khóa'), ('account_unlocked', 'Tài khoản được mở'), ('profile_updated', 'Cập nhật hồ sơ'), ('other', 'Khác')], max_length=50),
        ),
    ]
