# Generated by Django 5.0.14 on 2025-11-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_alter_selleractivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Lý do từ chối (nếu status = rejected)', null=True),
        ),
    ]
