# Generated by Django 5.0.14 on 2025-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_alter_seller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối'), ('active', 'Đang hoạt động'), ('locked', 'Đã khóa')], default='pending', max_length=20),
        ),
    ]
