# Generated by Django 5.0.14 on 2025-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_seller_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_type',
            field=models.CharField(blank=True, choices=[('personal', 'Cá nhân'), ('business', 'Doanh nghiệp'), ('household', 'Hộ kinh doanh')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='cccd_back',
            field=models.ImageField(blank=True, null=True, upload_to='cccd/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='cccd_front',
            field=models.ImageField(blank=True, null=True, upload_to='cccd/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
