# Generated by Django 5.0.14 on 2025-12-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_seller_business_license_seller_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
