# Generated by Django 5.0.14 on 2025-09-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_alter_shop_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
