<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-12-26 13:50
=======
# Generated by Django 5.0.14 on 2025-12-26 03:47
>>>>>>> MinhKhanh

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
