<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-12-26 03:24
=======
# Generated by Django 5.0.14 on 2025-12-26 03:54
>>>>>>> origin/TruongAn

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_featured', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PendingProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('availability_status', models.CharField(blank=True, max_length=20)),
                ('season_start', models.DateField(blank=True, null=True)),
                ('season_end', models.DateField(blank=True, null=True)),
                ('weight_g', models.IntegerField(default=1000, verbose_name='Cân nặng (gram)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Lít'), ('ml', 'Milliliter'), ('unit', 'Cái / Chiếc')], default='kg', max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sold', models.IntegerField(blank=True, default=0)),
                ('weight_g', models.IntegerField(default=1000, verbose_name='Cân nặng (gram)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_quantity', models.PositiveIntegerField(default=10)),
                ('ordered_quantity', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('banned', 'Banned'), ('hidden', 'Hidden'), ('pending_update', 'Chờ duyệt cập nhật')], default='pending', max_length=20)),
                ('tax_rate', models.IntegerField(choices=[(0, '0% (Miễn thuế/KCT)'), (5, '5% (Nông sản sơ chế)'), (8, '8% (Ưu đãi)'), (10, '10% (Thông thường)')], default=0, verbose_name='Thuế suất GTGT (%)')),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('availability_status', models.CharField(choices=[('available', 'Có sẵn'), ('coming_soon', 'Sắp có')], default='available', max_length=20)),
                ('season_start', models.DateField(blank=True, null=True)),
                ('season_end', models.DateField(blank=True, null=True)),
                ('import_request_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
