# Generated by Django 5.0.14 on 2025-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Lít'), ('ml', 'Milliliter'), ('unit', 'Cái / Chiếc')], default='kg', max_length=10),
        ),
    ]
