# Generated by Django 5.0.14 on 2025-08-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
