# Generated by Django 5.0.14 on 2025-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_request_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
