# Generated by Django 5.0.14 on 2025-12-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='Lý do từ chối sản phẩm (nếu có)', null=True),
        ),
    ]
