# Generated by Django 5.0.14 on 2025-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.IntegerField(default=1000, verbose_name='Cân nặng (gram)'),
        ),
    ]
