# Generated by Django 5.0.14 on 2025-10-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
    ]
