# Generated by Django 5.0.14 on 2025-12-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_import_request_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingproductupdate',
            name='weight_g',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_g',
        ),
    ]
