# Generated by Django 5.0.14 on 2025-12-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
