# Generated by Django 5.0.14 on 2025-10-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
