# Generated by Django 5.0.14 on 2025-11-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_normalized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ordered_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
