# Generated by Django 5.0.14 on 2025-08-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_is_best_seller_remove_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
