# Generated by Django 5.0.14 on 2025-08-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_status_subcategory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='status',
        ),
    ]
