# Generated by Django 5.0.14 on 2025-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_category_status_remove_subcategory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
