# Generated by Django 5.0.14 on 2025-11-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission_rate',
            field=models.FloatField(default=0.05),
        ),
    ]
