# Generated by Django 5.0.14 on 2025-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Có sẵn'), ('coming_soon', 'Sắp có')], default='available', max_length=20),
        ),
    ]
