# Generated by Django 5.0.14 on 2025-12-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
