# Generated by Django 5.0.14 on 2025-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
