# Generated by Django 5.0.14 on 2025-12-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('self_rejected', 'Self Rejected'), ('banned', 'Banned'), ('hidden', 'Hidden')], default='pending', max_length=20),
        ),
    ]
