# Generated by Django 5.0.14 on 2025-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_estimated_quantity_product_season_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordered_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
