# Generated by Django 5.0.14 on 2025-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='estimated_quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('banned', 'Banned'), ('hidden', 'Hidden'), ('pending_update', 'Chờ duyệt cập nhật')], default='pending', max_length=20),
        ),
    ]
