# Generated by Django 5.0.14 on 2025-10-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_preorder_product_alter_preorder_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preorder',
        ),
    ]
