# Generated by Django 5.0.14 on 2025-12-09 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_estimated_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('availability_status', models.CharField(blank=True, max_length=20)),
                ('season_start', models.DateField(blank=True, null=True)),
                ('season_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_update', to='products.product')),
            ],
        ),
    ]
