# Generated by Django 5.0.14 on 2025-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettopuprequest',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
