# Generated by Django 5.0.14 on 2025-09-05 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='advertisements/')),
                ('redirect_link', models.URLField(blank=True, help_text='Link dẫn đến sản phẩm/trang khuyến mãi', null=True)),
                ('ad_type', models.CharField(choices=[('popup', 'Popup Modal'), ('banner', 'Banner'), ('flash_sale', 'Flash Sale'), ('home_top', 'Home Top Banner'), ('home_middle', 'Home Middle Banner'), ('home_bottom', 'Home Bottom Banner')], default='banner', max_length=50)),
                ('target_type', models.CharField(choices=[('all_users', 'Tất cả người dùng'), ('new_users', 'Khách hàng mới'), ('returning_users', 'Khách quay lại'), ('vip_users', 'Khách VIP'), ('seller', 'Người bán'), ('custom', 'Tùy chỉnh')], default='all_users', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Thứ tự ưu tiên hiển thị, số nhỏ hiện trước')),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
