# Generated by Django 5.0.14 on 2025-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['priority', '-created_at'], 'permissions': [('can_manage_ads', 'Can manage advertisements')], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('home_top', 'Trang chủ - Phía trên'), ('home_middle', 'Trang chủ - Giữa'), ('home_bottom', 'Trang chủ - Dưới'), ('sidebar', 'Sidebar'), ('product_page', 'Trang sản phẩm'), ('checkout', 'Trang thanh toán')], default='home_top', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('popup', 'Popup Modal'), ('banner', 'Banner'), ('flash_sale', 'Flash Sale')], default='banner', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Thứ tự ưu tiên, số nhỏ hiển thị trước'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='redirect_link',
            field=models.URLField(blank=True, help_text='Link dẫn đến sản phẩm hoặc trang khuyến mãi', null=True),
        ),
    ]
