<<<<<<< HEAD
=======
# Generated by Django 5.0.14 on 2025-12-25 04:23
>>>>>>> origin/ChiTham

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('voucher', 'Voucher'), ('flashsale', 'Flash Sale')], default='voucher', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_scope', models.CharField(choices=[('ALL', 'Tất cả sản phẩm của cửa hàng'), ('CATEGORY', 'Theo danh mục'), ('SPECIFIC', 'Sản phẩm tùy chọn')], default='ALL', help_text='Áp dụng cho sản phẩm nào của cửa hàng', max_length=10)),
                ('distribution_type', models.CharField(choices=[('claim', 'Kho voucher (người dùng phải nhận)'), ('direct', 'Push thẳng vào tài khoản user')], default='claim', max_length=10)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('system', 'Hệ thống'), ('seller', 'Seller')], default='system', max_length=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('freeship_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='Tổng số lượng phát hành')),
                ('used_quantity', models.PositiveIntegerField(default=0, help_text='Số lượng đã sử dụng thực tế')),
                ('per_user_quantity', models.PositiveIntegerField(default=1)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền giảm')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử dùng Voucher',
                'verbose_name_plural': 'Lịch sử dùng Voucher',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> origin/ChiTham
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='flash_sales', to='products.product')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashsale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashsale_products', to='promotions.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
