# Generated by Django 5.0.14 on 2025-09-24 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_product_is_hidden_alter_product_status'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('voucher', 'Voucher'), ('flashsale', 'Flash Sale')], default='voucher', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_type', models.CharField(choices=[('claim', 'Kho voucher (người dùng phải nhận)'), ('direct', 'Push thẳng vào tài khoản user')], default='claim', max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('system', 'Hệ thống'), ('seller', 'Seller')], default='system', max_length=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('freeship_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, help_text='Tổng số lượng voucher (pool). Null = không giới hạn', null=True)),
                ('per_user_quantity', models.PositiveIntegerField(blank=True, default=1, help_text='Số lượng cấp cho 1 user khi nhận / được push', null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='promotions.promotion')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=0, editable=False, max_digits=12)),
                ('flash_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale', to='products.product')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['is_active', 'start_time', 'end_time'], name='promotions__is_acti_cf87a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='promotions.voucher')),
            ],
            options={
                'unique_together': {('user', 'voucher')},
            },
        ),
    ]
