# Generated by Django 5.0.14 on 2025-09-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsale',
            name='flash_price',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='stock',
        ),
    ]
