# Generated by Django 5.0.14 on 2025-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
