# Generated by Django 5.0.14 on 2025-09-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
