# Generated by Django 5.0.14 on 2025-12-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='used_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Số lượng đã sử dụng thực tế'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='per_user_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='product_scope',
            field=models.CharField(choices=[('ALL', 'Tất cả sản phẩm của cửa hàng'), ('CATEGORY', 'Theo danh mục'), ('SPECIFIC', 'Sản phẩm tùy chọn')], default='ALL', help_text='Áp dụng cho sản phẩm nào của cửa hàng', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Tổng số lượng phát hành'),
        ),
    ]
