# Generated by Django 5.0.14 on 2025-12-26 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_initial'),
        ('promotions', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Danh sách sản phẩm được áp dụng nếu product_scope là SPECIFIC', to='products.product'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='sellers.seller'),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='promotions.voucher'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usages', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usages', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='promotions.voucher', verbose_name='Voucher'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='promotions__is_acti_cf87a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleproduct',
            unique_together={('flashsale', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='uservoucher',
            unique_together={('user', 'voucher')},
        ),
    ]
