# Generated by Django 5.0.14 on 2025-09-06 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='used_count',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='usage_limit',
        ),
        migrations.AddField(
            model_name='promotion',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 6, 12, 31, 4, 262384, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='Default Voucher', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 6, 12, 32, 41, 537478, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('Promotion', 'Giảm tiền'), ('Flash Sale', 'Giảm %'), ('Voucher', 'Freeship')], default='voucher', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
