# Generated by Django 5.0.14 on 2025-10-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('sellers', '0011_sellerfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='sellers.seller'),
        ),
    ]
