# Generated by Django 5.0.14 on 2025-09-05 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_flashsale_storevoucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashSale',
        ),
        migrations.DeleteModel(
            name='StoreVoucher',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='used_count',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='start_at',
        ),
        migrations.AddField(
            model_name='promotion',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='Promotion thử', max_length=255),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('Promotion', 'Promotion'), ('Flash Sale', 'Flash Sale'), ('Voucher', 'Voucher')], default='Promotion', max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='CODE000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
