# Generated by Django 5.0.14 on 2025-12-24 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('promotions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền giảm')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian dùng')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usages', to='orders.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usages', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='promotions.voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Lịch sử dùng Voucher',
                'verbose_name_plural': 'Lịch sử dùng Voucher',
                'ordering': ['-used_at'],
            },
        ),
    ]
