# Generated by Django 5.0.14 on 2025-10-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_discount_percent'),
        ('promotions', '0002_alter_voucher_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Danh sách sản phẩm được áp dụng nếu product_scope là SPECIFIC', to='products.product'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='product_scope',
            field=models.CharField(choices=[('ALL', 'Tất cả sản phẩm của cửa hàng'), ('SPECIFIC', 'Sản phẩm tùy chọn')], default='ALL', help_text='Áp dụng cho sản phẩm nào của cửa hàng', max_length=10),
        ),
    ]
