# Generated by Django 5.0.14 on 2025-09-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_flashsale_voucher_flashsaleitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
