# Generated by Django 5.0.14 on 2025-09-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_is_hidden_alter_product_status'),
        ('promotions', '0002_alter_voucher_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsale',
            old_name='end_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='flashsale',
            old_name='flashsale_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flashsale',
            old_name='start_at',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='remaining_stock',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='total_stock',
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashsale_items', to='products.product')),
            ],
            options={
                'unique_together': {('flash_sale', 'product')},
            },
        ),
    ]
