# Generated by Django 5.0.14 on 2025-09-17 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_rename_end_at_flashsale_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='distribution_type',
            field=models.CharField(choices=[('claim', 'Kho voucher (người dùng phải nhận)'), ('direct', 'Push thẳng vào tài khoản user')], default='claim', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='per_user_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Số lượng cấp cho 1 user khi nhận / được push'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Tổng số lượng voucher (pool). Null = không giới hạn', null=True),
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='promotions.voucher')),
            ],
            options={
                'unique_together': {('user', 'voucher')},
            },
        ),
    ]
