# Generated by Django 5.0.14 on 2025-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_delete_flashsale_delete_storevoucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
