# Generated by Django 5.0.14 on 2025-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_voucher_distribution_type_voucher_per_user_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='per_user_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Số lượng cấp cho 1 user khi nhận / được push', null=True),
        ),
    ]
