# Generated by Django 5.0.14 on 2025-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promotion_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='code',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='usage_limit',
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_display',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='promotion',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('Promotion', 'Promotion'), ('Flash Sale', 'Flash Sale'), ('Voucher', 'Voucher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
