# Generated by Django 5.0.14 on 2025-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_remove_promotion_active_remove_promotion_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_display',
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
