# Generated by Django 5.2.7 on 2025-12-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(choices=[('about', 'Về GreenFarm'), ('policy', 'Chính sách'), ('help', 'Trung tâm trợ giúp')], default='help', max_length=32)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='pages/banners/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
