# Generated by Django 5.0.14 on 2025-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('refund_full', 'Hoàn tiền toàn bộ'), ('refund_partial', 'Hoàn tiền một phần'), ('replace', 'Đổi sản phẩm'), ('voucher', 'Tặng voucher/điểm thưởng'), ('reject', 'Từ chối khiếu nại')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/')),
            ],
        ),
    ]
