# Generated by Django 5.0.14 on 2025-09-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmedia',
            name='file',
            field=models.FileField(upload_to='complaints/'),
        ),
    ]
