<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-12-26 13:50
=======
# Generated by Django 5.0.14 on 2025-12-26 06:49
>>>>>>> origin/NhatNguyen

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='orders.orderitem'),
        ),
    ]
