# Generated by Django 5.0.14 on 2025-09-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaintmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
