# Generated by Django 5.0.14 on 2025-09-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_seller'),
        ('products', '0012_category_status_subcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='products.product'),
        ),
    ]
