# Generated by Django 5.0.14 on 2025-09-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='quantity',
        ),
    ]
