# Generated by Django 5.0.14 on 2025-12-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='return_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/proofs/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='return_shipping_carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='return_tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ người bán phản hồi'), ('negotiating', 'Đang thương lượng'), ('waiting_return', 'Shop đồng ý - Chờ gửi hàng'), ('returning', 'Đang trả hàng về'), ('admin_review', 'Sàn đang xem xét'), ('resolved_refund', 'Đã hoàn tiền'), ('resolved_reject', 'Từ chối hoàn tiền'), ('cancelled', 'Đã hủy khiếu nại')], default='pending', max_length=50),
        ),
    ]
