# Generated by Django 5.0.14 on 2025-09-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
