# Generated by Django 5.0.14 on 2025-09-05 09:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaint_media_complaintmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
