# Generated by Django 5.0.14 on 2025-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_complaintmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('refund_full', 'Hoàn tiền toàn bộ'), ('refund_partial', 'Hoàn tiền một phần'), ('replace', 'Đổi sản phẩm'), ('voucher', 'Tặng voucher/điểm thưởng'), ('reject', 'Từ chối khiếu nại')], max_length=30, null=True),
        ),
    ]
