# Generated by Django 5.0.14 on 2025-12-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('point_exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('ranks', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Loyalty Setting',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
        migrations.CreateModel(
            name='MarketingAutomationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email', models.BooleanField(default=False)),
                ('enable_sms', models.BooleanField(default=False)),
                ('season_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_schedule', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_days', models.PositiveIntegerField(default=7)),
                ('return_products', models.JSONField(blank=True, default=list, null=True)),
                ('complaint_process', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, choices=[('ghn', 'Giao Hàng Nhanh'), ('ghtk', 'Giao Hàng Tiết Kiệm'), ('viettelpost', 'Viettel Post')], max_length=50, null=True)),
                ('fee_rule', models.TextField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='settings/banner/')),
                ('brand_color', models.CharField(default='#ffffff', max_length=20)),
                ('theme_event', models.CharField(choices=[('default', 'Mặc định'), ('tet', 'Tết'), ('noel', 'Noel'), ('summer', 'Mùa hè')], default='default', max_length=50)),
            ],
        ),
    ]
