# Generated by Django 5.0.14 on 2025-10-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_days', models.PositiveIntegerField(default=7)),
                ('return_products', models.JSONField(blank=True, default=list, null=True)),
                ('complaint_process', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
