# Generated by Django 5.0.14 on 2025-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_returnpolicysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAutomationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email', models.BooleanField(default=False)),
                ('enable_sms', models.BooleanField(default=False)),
                ('season_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_schedule', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
