# Generated by Django 5.0.14 on 2025-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_marketingautomationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('point_exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('ranks', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Loyalty Setting',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
    ]
