# Generated by Django 5.0.14 on 2025-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_loyaltysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='settings/banner/')),
                ('brand_color', models.CharField(default='#ffffff', max_length=20)),
                ('theme_event', models.CharField(choices=[('default', 'Mặc định'), ('tet', 'Tết'), ('noel', 'Noel'), ('summer', 'Mùa hè')], default='default', max_length=50)),
            ],
        ),
    ]
