# Generated by Django 5.0.14 on 2025-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='MOMO', max_length=50),
        ),
    ]
