# Generated by Django 5.0.14 on 2025-12-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdraw', 'Rút tiền'), ('pending_income', 'Doanh thu chờ duyệt'), ('sale_income', 'Doanh thu bán hàng'), ('refund_deduct', 'Trừ tiền hoàn hàng'), ('platform_fee', 'Phí sàn')], max_length=20),
        ),
    ]
