# Generated by Django 5.0.14 on 2025-09-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='momo_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
