# Generated by Django 5.0.14 on 2025-11-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_sellerwallet_wallettransaction'),
        ('sellers', '0005_alter_selleractivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerwallet',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='sellers.seller'),
        ),
    ]
