# Generated by Django 5.0.14 on 2025-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_withdrawrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='momo_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='vnp_response_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnp_transaction_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
