# Generated by Django 5.0.14 on 2025-11-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_sellerwallet_updated_at_alter_sellerwallet_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='last_pending_approved_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian pending_balance được duyệt cuối cùng', null=True),
        ),
    ]
