# Generated by Django 5.0.14 on 2025-12-14 10:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='assets/users/')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và gồm đúng 10 chữ số.', regex='^0\\d{9}$')])),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pending_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_otp_expires', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động'), ('pending', 'Chờ duyệt')], default='active', max_length=10, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, help_text='Số dư ví tiền của người dùng', max_digits=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('district_id', models.IntegerField(blank=True, help_text='GHN DistrictID (bắt buộc nếu tính phí GHN)', null=True)),
                ('ward_code', models.CharField(blank=True, help_text='GHN WardCode (bắt buộc nếu tính phí GHN)', max_length=20, null=True)),
                ('province_code', models.CharField(blank=True, max_length=10, null=True)),
                ('district_code', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(default='Cộng điểm khi mua hàng', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_created', 'Đơn hàng mới'), ('order_status_changed', 'Cập nhật đơn hàng'), ('review_reply', 'Phản hồi đánh giá'), ('complaint', 'Khiếu nại'), ('wallet', 'Ví tiền'), ('voucher', 'Voucher'), ('system', 'Hệ thống')], default='system', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data like order_id, status, etc.', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền giao dịch', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdraw', 'Rút tiền'), ('payment', 'Chi tiêu'), ('refund', 'Hoàn tiền'), ('adjustment', 'Điều chỉnh')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Mô tả giao dịch', null=True)),
                ('reference_id', models.CharField(blank=True, help_text='ID đơn hàng, hoàn tiền, v.v.', max_length=100, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Số dư trước giao dịch', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Số dư sau giao dịch', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_userw_user_id_f61b2c_idx')],
            },
        ),
    ]
