# Generated by Django 5.2.7 on 2025-12-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Tên chủ tài khoản', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(blank=True, help_text='Số tài khoản ngân hàng', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Tên ngân hàng', max_length=100, null=True),
        ),
    ]
