# Generated by Django 5.0.14 on 2025-10-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_created', 'Đơn hàng mới'), ('order_status_changed', 'Cập nhật đơn hàng'), ('review_reply', 'Phản hồi đánh giá'), ('complaint', 'Khiếu nại'), ('wallet', 'Ví tiền'), ('voucher', 'Voucher'), ('system', 'Hệ thống')], default='system', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data like order_id, status, etc.', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx')],
            },
        ),
    ]
