# Generated by Django 5.0.14 on 2025-11-19 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số dư ví tiền của người dùng', max_digits=12),
        ),
        migrations.CreateModel(
            name='UserWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền giao dịch', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdraw', 'Rút tiền'), ('payment', 'Chi tiêu'), ('refund', 'Hoàn tiền'), ('adjustment', 'Điều chỉnh')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Mô tả giao dịch', null=True)),
                ('reference_id', models.CharField(blank=True, help_text='ID đơn hàng, hoàn tiền, v.v.', max_length=100, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Số dư trước giao dịch', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Số dư sau giao dịch', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_userw_user_id_f61b2c_idx')],
            },
        ),
    ]
