# Generated by Django 5.0.14 on 2025-08-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('employee', 'Employee'), ('cashier', 'Cashier'), ('chef', 'Chef')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
