# Generated by Django 5.0.14 on 2025-12-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_created', 'Đơn hàng mới'), ('order_status_changed', 'Cập nhật đơn hàng'), ('review_reply', 'Phản hồi đánh giá'), ('complaint', 'Khiếu nại'), ('refund', 'Hoàn tiền'), ('wallet', 'Ví tiền'), ('voucher', 'Voucher'), ('system', 'Hệ thống'), ('order', 'Đơn hàng'), ('chat', 'Tin nhắn'), ('promo', 'Khuyến mãi')], default='system', max_length=50),
        ),
    ]
