# Generated by Django 5.0.14 on 2025-08-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, default='customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
