# Generated by Django 5.0.14 on 2025-08-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_admin_customuser_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
