# Generated by Django 5.0.14 on 2025-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_admin_customuser_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
