# Generated by Django 5.0.14 on 2025-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động'), ('pending', 'Chờ duyệt')], max_length=10, null=True),
        ),
    ]
