# Generated by Django 5.0.14 on 2025-08-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_address_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
