# Generated by Django 5.0.14 on 2025-08-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pointhistory'),
        ('users', '0008_alter_customuser_is_staff'),
    ]

    operations = [
    ]
