# Generated by Django 5.0.14 on 2025-09-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_pending_email_customuser_pending_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động'), ('pending', 'Chờ duyệt')], default='active', max_length=10, null=True),
        ),
    ]
