# Generated by Django 5.0.14 on 2025-09-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_pending_email_customuser_pending_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district_id',
            field=models.IntegerField(blank=True, help_text='ID quận/huyện từ GHN', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ward_code',
            field=models.CharField(blank=True, help_text='Mã phường/xã từ GHN', max_length=20, null=True),
        ),
    ]
