# Generated by Django 5.0.14 on 2025-08-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20250815_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
