# Generated by Django 5.0.14 on 2025-09-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_district_id_customuser_ward_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ward_code',
        ),
        migrations.AddField(
            model_name='address',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ward_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
