# Generated by Django 5.0.14 on 2025-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_district_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district_id',
        ),
        migrations.AddField(
            model_name='address',
            name='district_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
