# Generated by Django 5.0.14 on 2025-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_address_district_id_address_district_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
