# Generated by Django 5.0.14 on 2025-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_address_province_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district_id',
            field=models.IntegerField(blank=True, help_text='GHN DistrictID', null=True),
        ),
    ]
