# Generated by Django 5.0.14 on 2025-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_address_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district_id',
            field=models.IntegerField(blank=True, help_text='GHN DistrictID (bắt buộc nếu tính phí GHN)', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward_code',
            field=models.CharField(blank=True, help_text='GHN WardCode (bắt buộc nếu tính phí GHN)', max_length=20, null=True),
        ),
    ]
